(() => {
  const namespace = window.SolarSystem;
  const raw = namespace?.domain?.catalogs?.rawDefinitions;
  if (!raw) {
    throw new Error("marker catalog bootstrap failed: missing raw definitions.");
  }

  namespace.domain.catalogs.markerCatalog = Object.freeze({
    DIRECTIONAL_MARKER_DEFINITIONS: raw.DIRECTIONAL_MARKER_DEFINITIONS,
    DIRECTIONAL_CONE_MAX_WIDTH_AU: raw.DIRECTIONAL_CONE_MAX_WIDTH_AU,
    DIRECTIONAL_CONE_TIP_RADIUS_AU: raw.DIRECTIONAL_CONE_TIP_RADIUS_AU,
    DIRECTIONAL_SOURCE_CONE_COLOR: raw.DIRECTIONAL_SOURCE_CONE_COLOR,
    DIRECTIONAL_SOURCE_CONE_DASH_PATTERN: raw.DIRECTIONAL_SOURCE_CONE_DASH_PATTERN,
    DIRECTIONAL_GUIDE_PARALLEL_SECTION_END_AU:
      raw.DIRECTIONAL_GUIDE_PARALLEL_SECTION_END_AU,
    DIRECTIONAL_GUIDE_POST_FOCAL_BASE_EXTENSION_AU:
      raw.DIRECTIONAL_GUIDE_POST_FOCAL_BASE_EXTENSION_AU,
    MATRYOSHKA_CONE_LAYER_DEFINITIONS: raw.MATRYOSHKA_CONE_LAYER_DEFINITIONS,
    DIRECTIONAL_MARKER_DISTANCE_AU: raw.DIRECTIONAL_MARKER_DISTANCE_AU
  });
})();
