(() => {
  const namespace = (window.SolarSystem = window.SolarSystem || {});
  const maxZoomAu = 6000;

  namespace.constants = Object.freeze({
    SCENE_OUTER_AU: 3000,
    HELIOSHEATH_INNER_AU: 92,
    HELIOPAUSE_AU: 120,
    HELIOPAUSE_MIXING_BAND_AU: 16,
    HELIOPAUSE_FLOW_DIRECTION: Object.freeze({ x: -1, y: 0.18, z: 0.05 }),
    SOLAR_GRAVITATIONAL_LENS_AU: 550,
    MIN_ZOOM_AU: 0.1,
    MAX_ZOOM_AU: maxZoomAu,
    NEAR_CLIP: 0.08,
    PARTICLE_NEAR_FADE_START_AU: 0.2,
    PARTICLE_NEAR_FADE_END_AU: 12,
    PARTICLE_FAR_CULL_DISTANCE_AU: 500,
    PARTICLE_DISTANCE_GRADIENT_START_RATIO: 0.24,
    PARTICLE_DISTANCE_GRADIENT_MIN_KEEP_RATIO: 0.08,
    PARTICLE_DISTANCE_GRADIENT_EXPONENT: 1.4,
    PARTICLE_SQUARE_DOT_MAX_RADIUS_PX: 0.55,
    SCENE_SCREEN_RADIUS_RATIO: 0.44,
    INITIAL_SCENE_FIT_MULTIPLIER: 1.08,
    SUN_RADIUS_KM: 696340,
    KM_PER_AU: 149597870.7,
    ORBIT_COLOR: "#b0bdc1",
    OORT_CLOUD_COLOR: "#d4e4ff",
    LINEAR_ZOOM_FULL_SPAN_SCROLL_PX: 1000000,
    EARTH_MEAN_MOTION: 0.020,
    EARTH_OBLIQUITY_DEG_J2000: 23.4392911,
    FONT_STACK: '"Avenir Next", "Futura", "Trebuchet MS", sans-serif',
    BACKGROUND_COLOR: "#000000",
    SUN_BLOOM_STRENGTH: 1.4,
    SUN_BLOOM_RADIUS: 0.55,
    SUN_BLOOM_THRESHOLD: 0.72,
    STAR_COLOR: "#dbe6ff",
    VOYAGER_EPOCH_LABEL: "2026-03-01",
    INVISIBLE_REFERENCE_SPHERE_AU: maxZoomAu + 500
  });
})();
